# Generated by Django 4.2.4 on 2023-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, default='@gmail.com', max_length=150, null=True),
        ),
    ]
