# Generated by Django 4.2.4 on 2023-09-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
    ]
