# Generated by Django 4.2.4 on 2023-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='logo')),
                ('montheme', models.ImageField(upload_to='montheme')),
                ('carousel1', models.ImageField(upload_to='carousel1')),
                ('carousel2', models.ImageField(upload_to='carousel2')),
                ('carousel3', models.ImageField(upload_to='carousel3')),
                ('carousel4', models.ImageField(upload_to='carousel4')),
                ('fb_link', models.CharField(max_length=50)),
                ('insta_link', models.CharField(max_length=50)),
                ('youtube_link', models.CharField(max_length=50)),
                ('whatsapp_link', models.CharField(max_length=50)),
                ('developer_link', models.CharField(max_length=50)),
                ('copyright', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CompanyProfile',
                'verbose_name_plural': 'CompanyProfile',
                'db_table': 'CompanyProfile',
                'managed': True,
            },
        ),
    ]
