# Generated by Django 4.2.4 on 2023-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='thread_link',
            field=models.CharField(default='https://www.threads.net/@rccgfvp', max_length=50),
        ),
    ]
