# Generated by Django 4.2.4 on 2023-08-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0002_companyprofile_thread_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('fet_img', models.ImageField(upload_to='fet_img')),
                ('openheaven_link', models.CharField(max_length=50)),
                ('sunday_link', models.CharField(max_length=50)),
                ('csr', models.TextField()),
                ('mission', models.TextField()),
            ],
            options={
                'verbose_name': 'Features',
                'verbose_name_plural': 'Features',
                'db_table': 'Features',
                'managed': True,
            },
        ),
    ]
