# Generated by Django 4.2.4 on 2023-08-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0003_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='time',
            field=models.CharField(default='6:30pm-7:30pm', max_length=15),
        ),
    ]
