# Generated by Django 4.2.4 on 2023-08-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0004_features_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_header', models.CharField(max_length=50)),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('team3', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='team')),
                ('img2', models.ImageField(upload_to='team')),
                ('img3', models.ImageField(upload_to='team')),
                ('txt1', models.TextField()),
                ('txt2', models.TextField()),
                ('txt3', models.TextField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'About',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='features',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
