# Generated by Django 4.2.4 on 2023-08-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0005_about_alter_features_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testifier', models.CharField(max_length=50)),
                ('passport', models.ImageField(upload_to='testifier')),
                ('testimony', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
                'db_table': 'Testimony',
                'managed': True,
            },
        ),
    ]
