# Generated by Django 4.2.4 on 2023-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0006_testimonies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_title', models.CharField(max_length=50)),
                ('g_img', models.ImageField(upload_to='gallery')),
                ('span_info', models.TextField()),
                ('land_right2', models.BooleanField()),
                ('land_left2', models.BooleanField()),
                ('portrait_center1', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
                'db_table': 'Gallery',
                'managed': True,
            },
        ),
    ]
