# Generated by Django 4.2.4 on 2023-08-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Give',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_verse', models.CharField(max_length=50)),
                ('g_head', models.CharField(max_length=50)),
                ('offering_verse', models.CharField(max_length=50)),
                ('offering_acc_no', models.CharField(max_length=50)),
                ('tithe_verse', models.CharField(max_length=50)),
                ('tithe_acc_no', models.CharField(max_length=50)),
                ('Nehemiah_verse', models.CharField(max_length=50)),
                ('Nehemiah_acc_no', models.CharField(max_length=50)),
                ('slide1', models.ImageField(upload_to='project')),
                ('slide2', models.ImageField(upload_to='project')),
                ('slide3', models.ImageField(upload_to='project')),
                ('slide4', models.ImageField(upload_to='project')),
            ],
            options={
                'verbose_name': 'Give',
                'verbose_name_plural': 'Give',
                'db_table': 'give',
                'managed': True,
            },
        ),
    ]
