# Generated by Django 4.2.4 on 2023-08-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0009_give'),
    ]

    operations = [
        migrations.AlterField(
            model_name='give',
            name='Nehemiah_acc_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='give',
            name='Nehemiah_verse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='give',
            name='g_head',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='give',
            name='g_verse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='give',
            name='offering_acc_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='give',
            name='offering_verse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='give',
            name='tithe_acc_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='give',
            name='tithe_verse',
            field=models.CharField(max_length=100),
        ),
    ]
