# Generated by Django 4.2.4 on 2023-09-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0010_alter_give_nehemiah_acc_no_alter_give_nehemiah_verse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.ImageField(upload_to='activities')),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
                ('content', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activity',
                'managed': True,
            },
        ),
    ]
