# Generated by Django 4.2.4 on 2023-09-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0012_activity_liked_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='group_whatsapp',
            field=models.CharField(default='@flourish_whatsapp', max_length=300),
        ),
    ]
