# Generated by Django 4.2.4 on 2023-09-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fvp', '0014_companyprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_info', models.TextField()),
                ('period', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
